const json = (x, status = 200, headers = {}) => new Response(JSON.stringify(x), { status, headers: { 'content-type': 'application/json;charset=UTF-8', ...headers } });
const b64 = x => btoa(String.fromCharCode(...new Uint8Array(x))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
const unb64 = x => Uint8Array.from(atob(x.replaceAll('-','+').replaceAll('_','/') + '==='.slice((x.length + 3) % 4)), c => c.charCodeAt(0));
const enc = new TextEncoder();
async function key(secret, use) { return crypto.subtle.importKey('raw', enc.encode(secret), { name: 'HMAC', hash: 'SHA-256' }, false, [use]); }
async function sign(payload, secret) { const body = b64(enc.encode(JSON.stringify(payload))); const sig = b64(await crypto.subtle.sign('HMAC', await key(secret,'sign'), enc.encode(body))); return `${body}.${sig}`; }
async function auth(request, env) { const token = (request.headers.get('cookie') || '').match(/session=([^;]+)/)?.[1]; if (!token) return null; const [body, sig] = token.split('.'); if (!body || !sig) return null; const ok = await crypto.subtle.verify('HMAC', await key(env.SESSION_SECRET,'verify'), unb64(sig), enc.encode(body)); if (!ok) return null; const user = JSON.parse(new TextDecoder().decode(unb64(body))); return user.exp > Date.now() ? user : null; }
async function hash(password, salt = crypto.getRandomValues(new Uint8Array(16))) { const raw = await crypto.subtle.deriveBits({ name:'PBKDF2', salt, iterations:100000, hash:'SHA-256' }, await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']), 256); return `${b64(salt)}:${b64(raw)}`; }
async function verify(password, stored) { const [salt, expected] = stored.split(':'); return (await hash(password, unb64(salt))).split(':')[1] === expected; }
async function boot(env) { await env.DB.batch([
  env.DB.prepare('CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, username TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, role TEXT NOT NULL)'),
  env.DB.prepare('CREATE TABLE IF NOT EXISTS teams (id INTEGER PRIMARY KEY, name TEXT NOT NULL)'),
  env.DB.prepare('CREATE TABLE IF NOT EXISTS team_users (team_id INTEGER,user_id INTEGER,PRIMARY KEY(team_id,user_id))'),
  env.DB.prepare('CREATE TABLE IF NOT EXISTS team_data (team_id INTEGER,key TEXT,value TEXT,PRIMARY KEY(team_id,key))')
 ]); const any=await env.DB.prepare('SELECT id FROM users LIMIT 1').first(); if(!any){ if(!env.ADMIN_PASSWORD||!env.SESSION_SECRET)throw new Error('Missing required secrets'); const t=(await env.DB.prepare('INSERT INTO teams(name) VALUES(?)').bind('默认球队').run()).meta.last_row_id; const u=(await env.DB.prepare('INSERT INTO users(username,password_hash,role) VALUES(?,?,?)').bind(env.ADMIN_USERNAME||'admin',await hash(env.ADMIN_PASSWORD),'admin').run()).meta.last_row_id; await env.DB.prepare('INSERT INTO team_users VALUES(?,?)').bind(t,u).run(); } }
async function data(env, team, key, def){ const r=await env.DB.prepare('SELECT value FROM team_data WHERE team_id=? AND key=?').bind(team,key).first(); return r?JSON.parse(r.value):def; }
async function save(env, team, key, value){ await env.DB.prepare('INSERT INTO team_data VALUES(?,?,?) ON CONFLICT(team_id,key) DO UPDATE SET value=excluded.value').bind(team,key,JSON.stringify(value)).run(); }
const deny=()=>json({error:'forbidden'},403);
function visible(matches,user){ return matches.map(m=>{const c=structuredClone(m),v=c.mvpVote;if(v){const results=Object.fromEntries(v.candidateIds.map(id=>[id,0]));Object.values(v.ballots||{}).flat().forEach(id=>{if(id in results)results[id]++});v.results=results;if(user.role!=='admin'){const own=v.ballots?.[String(user.id)]||[];v.ballots=own.length?{[user.id]:own}:{};}}return c;}); }
async function api(request,env,url){ await boot(env); const path=url.pathname, user=await auth(request,env); const body=async()=>request.json().catch(()=>({})); if(path==='/api/login'&&request.method==='POST'){const d=await body(),r=await env.DB.prepare('SELECT * FROM users WHERE username=?').bind(String(d.username||'').trim()).first();if(!r||!(await verify(String(d.password||''),r.password_hash)))return json({error:'登录失败'},401);const m=await env.DB.prepare('SELECT team_id FROM team_users WHERE user_id=? LIMIT 1').bind(r.id).first();const u={id:r.id,username:r.username,role:r.role,teamId:m.team_id,exp:Date.now()+30*864e5};return json({ok:true,user:{id:u.id,username:u.username,role:u.role}},200,{'Set-Cookie':`session=${await sign(u,env.SESSION_SECRET)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=2592000`});}
 if(path==='/api/logout')return json({ok:true},200,{'Set-Cookie':'session=; Path=/; Max-Age=0'}); if(path==='/api/check-auth')return json({authed:!!user,user:user&&{id:user.id,username:user.username,role:user.role}}); if(!user)return json({error:'unauthorized'},401);
 if(path==='/api/data'&&request.method==='GET')return json({players:await data(env,user.teamId,'players',[]),matches:visible(await data(env,user.teamId,'matches',[]),user)});
 if(path==='/api/players'&&request.method==='POST'){if(user.role!=='admin')return deny();const d=await body();if(!Array.isArray(d))return json({error:'invalid'},400);await save(env,user.teamId,'players',d);return json({ok:true});}
 if(path==='/api/matches'&&request.method==='POST'){const incoming=await body();if(!Array.isArray(incoming))return json({error:'invalid'},400);let matches=incoming;if(user.role!=='admin'){const old=await data(env,user.teamId,'matches',[]),by=new Map(incoming.map(x=>[x.id,x]));matches=old.map(x=>{const n=by.get(x.id)||{},o={...x};for(const k of ['roster','starters','substitutes','lineups'])if(n[k]&&typeof n[k]===typeof x[k])o[k]=n[k];return o;});}await save(env,user.teamId,'matches',matches);return json({ok:true});}
 if(path==='/api/admin/users'){if(user.role!=='admin')return deny();if(request.method==='GET'){const r=await env.DB.prepare('SELECT u.id,u.username,u.role FROM users u JOIN team_users t ON t.user_id=u.id WHERE t.team_id=?').bind(user.teamId).all();return json({users:r.results});}const d=await body();if(!/^[\w.-]{3,32}$/.test(d.username||'')||typeof d.password!=='string'||d.password.length<8)return json({error:'用户名或密码不合规'},400);try{const id=(await env.DB.prepare('INSERT INTO users(username,password_hash,role) VALUES(?,?,?)').bind(d.username,await hash(d.password),d.role==='admin'?'admin':'member').run()).meta.last_row_id;await env.DB.prepare('INSERT INTO team_users VALUES(?,?)').bind(user.teamId,id).run();return json({ok:true});}catch{return json({error:'用户名已存在'},409)}}
 if(path==='/api/account/password'&&request.method==='POST'){const d=await body(),r=await env.DB.prepare('SELECT password_hash FROM users WHERE id=?').bind(user.id).first();if(!r || !(await verify(d.current_password||'',r.password_hash)) || typeof d.new_password!=='string' || d.new_password.length<8) return json({error:'修改失败'},400);await env.DB.prepare('UPDATE users SET password_hash=? WHERE id=?').bind(await hash(d.new_password),user.id).run();return json({ok:true});}
 const vote=path.match(/^\/api\/matches\/([^/]+)\/mvp-vote(\/configure)?$/);if(vote&&request.method==='POST'){let ms=await data(env,user.teamId,'matches',[]),m=ms.find(x=>x.id===decodeURIComponent(vote[1]));if(!m)return json({error:'not found'},404);const d=await body();if(vote[2]){if(user.role!=='admin')return deny();m.mvpVote={voterIds:d.voterIds||[],candidateIds:d.candidateIds||[],votesPerUser:d.votesPerUser||1,ballots:{}};}else{const v=m.mvpVote,ids=d.candidateIds||[];if(!v||!v.voterIds.includes(user.id)||!ids.length||ids.length>v.votesPerUser||new Set(ids).size!==ids.length||!ids.every(x=>v.candidateIds.includes(x)))return deny();v.ballots[String(user.id)]=ids;}await save(env,user.teamId,'matches',ms);return json({ok:true});}return json({error:'not found'},404); }
export default { async fetch(request,env){const url=new URL(request.url);return url.pathname.startsWith('/api/')?api(request,env,url):env.ASSETS.fetch(request);} };